title = "ILAS2025"
baseURL = "https://ilas2025.tw/"
# baseURL = "https://ilas2025.github.io/"
# languageCode = "en-us"
# theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
theme = "ananke"
resourceDir = "../resources"

# DefaultContentLanguage = "en"
# SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

### rooted parameters need to be on the top
### added by Jephian ###
# enableEmoji = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = "images/favicon.ico"
  site_logo = "images/ILAS2025-logo-dark.svg"
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
  custom_css = ["css/custom.css"]

# [[params.ananke_socials]]
# name = "twitter"
# url = "https://twitter.com/GoHugoIO"


##### above are modified from themes/ananke/exampleSite/config.toml #####
##### below are new things added by Jephian #####

# To use raw html in the content, set unsafe as true.
# [markup]
#   [markup.goldmark]
#     [markup.goldmark.renderer]
#       unsafe = false

[menu]
[[menu.main]]
  name = 'Taiwan'
  URL = '/taiwan/'
  weight = 10
[[menu.main]]
  name = 'Registration'
  URL = '/registration/'
  weight = 20
[[menu.main]]
  name = 'Program'
  URL = '/program/'
  weight = 30
[[menu.main]]
  name = 'About'
  URL = '/about/'
  weight = 40

[[menu.main]]
  parent = 'Taiwan'
  name = 'Plan your trip'
  URL = '/taiwan/travel/'
  weight = 11
[[menu.main]]
  parent = 'Taiwan'
  name = 'Local'
  URL = '/taiwan/local/'
  weight = 12
[[menu.main]]
  parent = 'About'
  name = 'Inclusiveness statement'
  URL = '/about/inclusiveness-statement/'
  weight = 41