title = "ILAS2025"
baseURL = "https://ilas2025.tw/"
# baseURL = "https://ilas2025.github.io/"
# languageCode = "en-us"
# theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
theme = "ananke"
resourceDir = "../resources"

# DefaultContentLanguage = "en"
# SectionPagesMenu = "main"
# Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

### rooted parameters need to be on the top
### added by Jephian ###
# enableEmoji = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = "images/favicon.ico"
  site_logo = "images/ILAS2025-logo-dark.svg"
  description = "The 26th Conference of the International Linear Algebra Society"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
  custom_css = ["css/custom.css"]
  env = "production" # for robots.txt
  # added for KaTex
  math = true

# [[params.ananke_socials]]
# name = "twitter"
# url = "https://twitter.com/GoHugoIO"


##### above are modified from themes/ananke/exampleSite/config.toml #####
##### below are new things added by Jephian #####

# added for KaTex
[markup]
  [markup.goldmark]
    # To use raw html in the content, set unsafe as true.
    # [markup.goldmark.renderer]
    #   unsafe = false
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]


[mount]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'

[menu]
[[menu.main]]
  name = 'Home'
  URL = '/'
  weight = 1
[[menu.main]]
  name = 'Taiwan'
  URL = '/taiwan/'
  weight = 10
[[menu.main]]
  name = 'Registration'
  URL = '/registration/'
  weight = 20
[[menu.main]]
  name = 'Program'
  URL = '/program/'
  weight = 30
[[menu.main]]
  name = 'About'
  URL = '/about/'
  weight = 40
[[menu.main]]
  name = 'LAA special issue'
  URL = '/laa/'
  weight = 40

[[menu.main]]
  parent = 'Taiwan'
  name = 'Plan your trip'
  URL = '/taiwan/travel/'
  weight = 11
[[menu.main]]
  parent = 'Taiwan'
  name = 'Local'
  URL = '/taiwan/local/'
  weight = 12
[[menu.main]]
  parent = 'Registration'
  name = 'Social events'
  URL = '/registration/social/'
  weight = 21
[[menu.main]]
  parent = 'Registration'
  name = 'Student support'
  URL = '/registration/student-support/'
  weight = 22
[[menu.main]]
  parent = 'Program'
  name = 'Schedule'
  URL = '/program/schedule/'
  weight = 30
[[menu.main]]
  parent = 'Program'
  name = 'Plenary speakers'
  URL = '/program/plenary/'
  weight = 31
[[menu.main]]
  parent = 'Program'
  name = 'Mini-symposia'
  URL = '/program/mini/'
  weight = 32
[[menu.main]]
  parent = 'Program'
  name = 'Contributed talks and posters'
  URL = '/program/contributed-and-poster/'
  weight = 33
[[menu.main]]
  parent = 'Program'
  name = 'Talks Similarity Dashboard'
  URL = '/program/talks-similarity-dashboard/'
  weight = 34
[[menu.main]]
  parent = 'About'
  name = 'LOGO'
  URL = '/about/logo/'
  weight = 41
[[menu.main]]
  parent = 'About'
  name = 'Inclusiveness statement'
  URL = '/about/inclusiveness-statement/'
  weight = 42